version: '3.8'

services:
  # PostgreSQL with pgvector
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #     - bootstrap.memory_lock=true
  #     - ELASTIC_USERNAME=${ELASTICSEARCH_USERNAME}
  #     - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - elasticsearch_data:/usr/share/elasticsearch/data
  #   restart: always

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: always

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data:
